server:
  port: 8083


# Configuration Keycloak

spring:
  application:
    name: ms_gestschool

  main:
    allow-bean-definition-overriding: true

  datasource:
    ######### SANS DOCKER #######################
    # url: jdbc:mysql://localhost:3306/db_school?useSSL=false&serverTimezone=UTC
    url: jdbc:postgresql://localhost:5432/db_school
    username: postgres
    password: Passer@1
    ################### AVEC DOCKER #################
    # url: jdbc:mysql://DATABASE:3306/db_school?useSSL=false&serverTimezone=UTC
    # username: appuser
    # password: Passer@1
    driver-class-name: org.postgresql.Driver

  jpa:
    # database-platform: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/school_realm
logging:
  level:
    org.springframework.web: DEBUG
  file:
    name: logs/logs.log



